# Generated by Django 2.2.1 on 2019-07-01 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20190618_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rave_id',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
