# Generated by Django 2.2.1 on 2019-06-08 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='name',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='storage',
            name='name',
            field=models.CharField(db_index=True, max_length=10),
        ),
    ]
