# Generated by Django 2.2.1 on 2019-06-08 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20190608_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='memory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Memory'),
        ),
    ]
