# Generated by Django 2.2.1 on 2019-07-05 19:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20190705_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fee',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MaxValueValidator(7000)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
